version: '3.1'

services:
  mongo:
    name:mongodb
    image: mongo
    restart: always
    # environment:
      #MongoDB 기본 패스워드 
      # MONGO_INITDB_ROOT_USERNAME: <ROOT User Name>
      # MONGO_INITDB_ROOT_PASSWORD: <ROOT User Password>
    # volumns:
    #   <Data를 보관할 폴더>:/data/db